package cn.com.cgh.gallery.notify.entity;

import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;

@Data
@Builder
public class Notify {
//    @TableId(autoGenerated = true)
    private BigDecimal id;
    private String avatar;// 头像
    private String title;// 标题
    private String datetime;// 时间 标题下的内容
    private String description;// 描述
    private String href;// () => "{href}/{name}"跳转地址
    private NotifyEm status;
    private String extra;//  title 额外信息
}
